using System.Web;
using org.g14.FeatureFlags.Generation.CodeProduction.Models;

namespace org.g14.FeatureFlags.Generation.CodeProduction;

/// <summary>
/// Creates text contents of source code files.
/// This implementation is simple, it focuses on readability.
/// </summary>
public class SimpleSourceCodeCreator(
    string defaultNamespace,
    CancellationToken? cancellationToken = null
) : ISourceCodeCreator
{
    public SourceCodeDetails GetAppsettingsObjectClass(
        string @namespace,
        PropDetails[] propsAndTheirTypes,
        string className)
    {
        cancellationToken?.ThrowIfCancellationRequested();

        IEnumerable<string> propsDefinitions = propsAndTheirTypes
            .Select(x => $"public required {x.PropType} {x.PropName} {{ get; init; }}");

        IEnumerable<string> usingStatements = propsAndTheirTypes
            .Select(x => x.RequiredNamespace)
            .Distinct()
            .Where(ns => ns != null)
            .Select(ns => $"using {ns};");

        return new(
            FileName: $"{className}.generated.cs",
            SourceCodeText:
            $$"""
              {{Const.AutogeneratedHeader}}

              {{string.Join("\n", usingStatements)}}

              namespace {{@namespace}};

              {{Const.GeneratedCodeAttribute}}
              public class {{className}}
              {
                  {{string.Join("\n    ", propsDefinitions)}}
              }
              """);
    }

    /// <summary>
    /// Create a very basic version of a class.
    /// This prevents some compilation errors (because the type is there)
    /// and allows to convey some details of the problem (in addition to regular diagnostics).
    /// </summary>
    public SourceCodeDetails GetErrorIndicatingClass(string errorMessage, string className)
    {
        cancellationToken?.ThrowIfCancellationRequested();

        return new(
            FileName: $"{className}.generated.cs",
            SourceCodeText:
            $$"""
              {{Const.AutogeneratedHeader}}
              
              namespace {{defaultNamespace}};

              {{Const.GeneratedCodeAttribute}}
              public class {{className}}
              {
                  /// <summary>
                  /// {{HttpUtility.HtmlEncode(errorMessage)}}
                  /// </summary>
                  public string COMPILATION_ERROR = "File could not be generated. See the doc comment of this property for details";
              }
              """);
    }

    /// <summary>
    /// The unknown type is used if the actual type for an appsettings item could not be determined.
    /// Possible causes: the generator does not support something, bug.
    /// </summary>
    public SourceCodeDetails GetUnknownTypeClass(string className)
    {
        cancellationToken?.ThrowIfCancellationRequested();

        return new(
            FileName: $"{className}.generated.cs",
            SourceCodeText:
            $$"""
              {{Const.AutogeneratedHeader}}
              
              namespace {{defaultNamespace}};

              /// <summary>
              /// The type of the item in appsettings could not be identified
              /// </summary>
              {{Const.GeneratedCodeAttribute}}
              public class {{className}}
              {
              }
              """);
    }

    public SourceCodeDetails GetServiceCollectionExtensionMethod(string className)
    {
        cancellationToken?.ThrowIfCancellationRequested();

        return new(
            FileName: "ServiceCollectionExtensions.generated.cs",
            SourceCodeText:
            $$"""
              {{Const.AutogeneratedHeader}}
              
              namespace {{defaultNamespace}};

              {{Const.GeneratedCodeAttribute}}
              public static class ServiceCollectionExtensions
              {
                  public static IServiceCollection AddGeneratedFeatureFlags(this IServiceCollection services)
                  {
                      return services.AddSingleton<{{className}}>(services =>
                      {
                          string key = "{{Const.FlagsRootKey}}";
                          IConfiguration configuration = services.GetRequiredService<IConfiguration>();
                          IConfigurationSection configSection = configuration.GetSection(key);
                          return configSection.Get<{{className}}>();
                      });
                  }
              }
              """);
    }
}