using NUnit.Framework;
using org.g14.FeatureFlags.Generation.CodeProduction;
using org.g14.FeatureFlags.Generation.CodeProduction.Models;
using static org.g14.FeatureFlags.Generation.Tests.TestHelpers;

namespace org.g14.FeatureFlags.Generation.Tests;

/** Tests the efficient source code creator:
    - Empty classes
    - Classes with single/multiple properties
    - Array properties (int[])
    - 2D array properties (int[][])
    - Using statements for required namespaces
    - Multiple namespace handling
    - Duplicate namespace deduplication
    - Error indicating classes with simple messages
    - Error classes with special character encoding
    - Unknown type class generation
    - Service collection extension method generation
 */

[TestFixture]
public class SimpleSourceCodeCreatorTests
{
    private SimpleSourceCodeCreator _creator = null!;
    private const string TestNamespace = "TestNamespace";

    [SetUp]
    public void SetUp()
    {
        _creator = new SimpleSourceCodeCreator(TestNamespace);
    }

    [Test]
    public void GetAppsettingsObjectClass_WithEmptyProperties_GeneratesEmptyClass()
    {
        // Arrange
        PropDetails[] props = Array.Empty<PropDetails>();
        string className = "EmptyClass";

        // Act
        SourceCodeDetails result = _creator.GetAppsettingsObjectClass(TestNamespace, props, className);

        // Assert
        string expected = $$"""
            {{Const.AutogeneratedHeader}}

            namespace TestNamespace;

            public class EmptyClass
            {
                
            }
            """;
        Assert.That(result.FileName, Is.EqualTo("EmptyClass.generated.cs"));
        Assert.That(NormalizeLineEndings(result.SourceCodeText), Is.EqualTo(NormalizeLineEndings(expected)));
    }

    [Test]
    public void GetAppsettingsObjectClass_WithSingleProperty_GeneratesClassWithOneProperty()
    {
        // Arrange
        PropDetails[] props = new[]
        {
            new PropDetails("string", null, "Name")
        };
        string className = "SimpleClass";

        // Act
        SourceCodeDetails result = _creator.GetAppsettingsObjectClass(TestNamespace, props, className);

        // Assert
        string expected = $$"""
            {{Const.AutogeneratedHeader}}
            
            namespace TestNamespace;

            public class SimpleClass
            {
                public required string Name { get; init; }
            }
            """;
        Assert.That(result.FileName, Is.EqualTo("SimpleClass.generated.cs"));
        Assert.That(NormalizeLineEndings(result.SourceCodeText), Is.EqualTo(NormalizeLineEndings(expected)));
    }

    [Test]
    public void GetAppsettingsObjectClass_WithMultipleProperties_GeneratesClassWithAllProperties()
    {
        // Arrange
        PropDetails[] props = new[]
        {
            new PropDetails("string", null, "Name"),
            new PropDetails("int", null, "Age"),
            new PropDetails("bool", null, "IsActive")
        };
        string className = "PersonClass";

        // Act
        SourceCodeDetails result = _creator.GetAppsettingsObjectClass(TestNamespace, props, className);

        // Assert
        string expected = $$"""
            {{Const.AutogeneratedHeader}}

            namespace TestNamespace;

            public class PersonClass
            {
                public required string Name { get; init; }
                public required int Age { get; init; }
                public required bool IsActive { get; init; }
            }
            """;
        Assert.That(result.FileName, Is.EqualTo("PersonClass.generated.cs"));
        Assert.That(NormalizeLineEndings(result.SourceCodeText), Is.EqualTo(NormalizeLineEndings(expected)));
    }

    [Test]
    public void GetAppsettingsObjectClass_WithArrayProperty_GeneratesArraySyntax()
    {
        // Arrange
        PropDetails[] props = new[]
        {
            new PropDetails("int[]", null, "Numbers")
        };
        string className = "ArrayClass";

        // Act
        SourceCodeDetails result = _creator.GetAppsettingsObjectClass(TestNamespace, props, className);

        // Assert
        string expected = $$"""
            {{Const.AutogeneratedHeader}}
            
            namespace TestNamespace;

            public class ArrayClass
            {
                public required int[] Numbers { get; init; }
            }
            """;
        Assert.That(result.FileName, Is.EqualTo("ArrayClass.generated.cs"));
        Assert.That(NormalizeLineEndings(result.SourceCodeText), Is.EqualTo(NormalizeLineEndings(expected)));
    }

    [Test]
    public void GetAppsettingsObjectClass_With2DArray_Generates2DArraySyntax()
    {
        // Arrange
        PropDetails[] props = new[]
        {
            new PropDetails("int[][]", null, "Matrix")
        };
        string className = "MatrixClass";

        // Act
        SourceCodeDetails result = _creator.GetAppsettingsObjectClass(TestNamespace, props, className);

        // Assert
        string expected = $$"""
            {{Const.AutogeneratedHeader}}

            namespace TestNamespace;

            public class MatrixClass
            {
                public required int[][] Matrix { get; init; }
            }
            """;
        Assert.That(result.FileName, Is.EqualTo("MatrixClass.generated.cs"));
        Assert.That(NormalizeLineEndings(result.SourceCodeText), Is.EqualTo(NormalizeLineEndings(expected)));
    }

    [Test]
    public void GetAppsettingsObjectClass_WithRequiredNamespace_IncludesUsingStatement()
    {
        // Arrange
        PropDetails[] props = new[]
        {
            new PropDetails("CustomType", "Custom.Namespace", "Data")
        };
        string className = "CustomClass";

        // Act
        SourceCodeDetails result = _creator.GetAppsettingsObjectClass(TestNamespace, props, className);

        // Assert
        string expected = $$"""
            {{Const.AutogeneratedHeader}}

            using Custom.Namespace;

            namespace TestNamespace;

            public class CustomClass
            {
                public required CustomType Data { get; init; }
            }
            """;
        Assert.That(result.FileName, Is.EqualTo("CustomClass.generated.cs"));
        Assert.That(NormalizeLineEndings(result.SourceCodeText), Is.EqualTo(NormalizeLineEndings(expected)));
    }

    [Test]
    public void GetAppsettingsObjectClass_WithMultipleNamespaces_IncludesAllUsingStatements()
    {
        // Arrange
        PropDetails[] props = new[]
        {
            new PropDetails("TypeA", "Namespace.A", "PropA"),
            new PropDetails("TypeB", "Namespace.B", "PropB"),
            new PropDetails("int", null, "PropC")
        };
        string className = "MultiNsClass";

        // Act
        SourceCodeDetails result = _creator.GetAppsettingsObjectClass(TestNamespace, props, className);

        // Assert
        string expected = $$"""
            {{Const.AutogeneratedHeader}}

            using Namespace.A;
            using Namespace.B;

            namespace TestNamespace;

            public class MultiNsClass
            {
                public required TypeA PropA { get; init; }
                public required TypeB PropB { get; init; }
                public required int PropC { get; init; }
            }
            """;
        Assert.That(result.FileName, Is.EqualTo("MultiNsClass.generated.cs"));
        Assert.That(NormalizeLineEndings(result.SourceCodeText), Is.EqualTo(NormalizeLineEndings(expected)));
    }

    [Test]
    public void GetAppsettingsObjectClass_WithDuplicateNamespaces_IncludesOnlyOneUsingStatement()
    {
        // Arrange
        PropDetails[] props = new[]
        {
            new PropDetails("TypeA", "Same.Namespace", "PropA"),
            new PropDetails("TypeB", "Same.Namespace", "PropB")
        };
        string className = "DuplicateNsClass";

        // Act
        SourceCodeDetails result = _creator.GetAppsettingsObjectClass(TestNamespace, props, className);

        // Assert
        string expected = $$"""
            {{Const.AutogeneratedHeader}}

            using Same.Namespace;

            namespace TestNamespace;

            public class DuplicateNsClass
            {
                public required TypeA PropA { get; init; }
                public required TypeB PropB { get; init; }
            }
            """;
        Assert.That(result.FileName, Is.EqualTo("DuplicateNsClass.generated.cs"));
        Assert.That(NormalizeLineEndings(result.SourceCodeText), Is.EqualTo(NormalizeLineEndings(expected)));
    }

    [Test]
    public void GetErrorIndicatingClass_WithSimpleMessage_GeneratesClassWithErrorProperty()
    {
        // Arrange
        string errorMessage = "Something went wrong";
        string className = "ErrorClass";

        // Act
        SourceCodeDetails result = _creator.GetErrorIndicatingClass(errorMessage, className);

        // Assert
        string expected = $$"""
            {{Const.AutogeneratedHeader}}

            namespace TestNamespace;

            public class ErrorClass
            {
                /// <summary>
                /// Something went wrong
                /// </summary>
                public string COMPILATION_ERROR = "File could not be generated. See the doc comment of this property for details";
            }
            """;
        Assert.That(result.FileName, Is.EqualTo("ErrorClass.generated.cs"));
        Assert.That(NormalizeLineEndings(result.SourceCodeText), Is.EqualTo(NormalizeLineEndings(expected)));
    }

    [Test]
    public void GetErrorIndicatingClass_WithSpecialCharacters_EncodesThemProperly()
    {
        // Arrange
        string errorMessage = "Error: <tag> & \"quotes\"";
        string className = "SpecialCharErrorClass";

        // Act
        SourceCodeDetails result = _creator.GetErrorIndicatingClass(errorMessage, className);

        // Assert
        string expected = $$"""
            {{Const.AutogeneratedHeader}}

            namespace TestNamespace;

            public class SpecialCharErrorClass
            {
                /// <summary>
                /// Error: &lt;tag&gt; &amp; &quot;quotes&quot;
                /// </summary>
                public string COMPILATION_ERROR = "File could not be generated. See the doc comment of this property for details";
            }
            """;
        Assert.That(result.FileName, Is.EqualTo("SpecialCharErrorClass.generated.cs"));
        Assert.That(NormalizeLineEndings(result.SourceCodeText), Is.EqualTo(NormalizeLineEndings(expected)));
    }

    [Test]
    public void GetUnknownTypeClass_GeneratesEmptyClassWithDocComment()
    {
        // Arrange
        string className = "UnknownClass";

        // Act
        SourceCodeDetails result = _creator.GetUnknownTypeClass(className);

        // Assert
        string expected = $$"""
            {{Const.AutogeneratedHeader}}

            namespace TestNamespace;

            /// <summary>
            /// The type of the item in appsettings could not be identified
            /// </summary>
            public class UnknownClass
            {
            }
            """;
        Assert.That(result.FileName, Is.EqualTo("UnknownClass.generated.cs"));
        Assert.That(NormalizeLineEndings(result.SourceCodeText), Is.EqualTo(NormalizeLineEndings(expected)));
    }

    [Test]
    public void GetServiceCollectionExtensionMethod_GeneratesExtensionMethodWithCorrectClassName()
    {
        // Arrange
        string className = "FlagsRootType";

        // Act
        SourceCodeDetails result = _creator.GetServiceCollectionExtensionMethod(className);

        // Assert
        string expected = $$"""
            {{Const.AutogeneratedHeader}}

            namespace TestNamespace;

            public static class ServiceCollectionExtensions
            {
                public static IServiceCollection AddGeneratedFeatureFlags(this IServiceCollection services)
                {
                    return services.AddSingleton<FlagsRootType>(services =>
                    {
                        string key = "FeatureFlags";
                        IConfiguration configuration = services.GetRequiredService<IConfiguration>();
                        IConfigurationSection configSection = configuration.GetSection(key);
                        return configSection.Get<FlagsRootType>();
                    });
                }
            }
            """;
        Assert.That(result.FileName, Is.EqualTo("ServiceCollectionExtensions.generated.cs"));
        Assert.That(NormalizeLineEndings(result.SourceCodeText), Is.EqualTo(NormalizeLineEndings(expected)));
    }
}