// using org.g14.FeatureFlags;

using UsageExample.GeneratedFeatureFlags;
using UsageExample.GeneratedFeatureFlags.TwoWayMessaging.RefreshIntervals;

var builder = Host.CreateApplicationBuilder(args);

// builder.Services.AddSingleton<IFeatureManager, FeatureManager>();

var host = builder.Build();

// IFeatureManager features = host.Services.GetService<IFeatureManager>()
//     ?? throw new InvalidOperationException("FeatureManager could not be retrieved from DI container");

Console.WriteLine("Hello, World!");

/*
if (features["TwoWayMessaging"].IsEnabled)
{
    Console.WriteLine("Two way messaging");
}

if (features["IncomeSupport"].IsEnabled)
{
    Console.WriteLine("Income Support");
    int n = features["IncomeSupport"].Get<int>("MagicNumber");
    Console.WriteLine($"     -- magic number is {n}");

    if (features["IncomeSupport.Page8"].IsEnabled)
    {
        Console.WriteLine("Page 8 of Income Support");
    }
}
*/

// namespaces/classes for when we generate:
// ...FeatureFlags.FlagsRoot
// ...FeatureFlags.FlagsRoot.TwoWayMessagingFlags
// ...FeatureFlags.FlagsRoot.IncomeSupportFlags
// ...FeatureFlags.FlagsRoot.IncomeSupportFlags.Page8Flags

// temporary: this will eventually be generated; located in .AddGeneratedFeatureFlags() service collection extension
FlagsRootType features = host.Services.GetRequiredService<FlagsRootType>();

features.TestBool = false;
bool b = features.TestBool;
features.TestBool = false; // TODO: assigning should not be possible (introducing the interfaces can fix that)
if (features.IncomeSupport.IsEnabled)
{
    Console.WriteLine("Income Support");
    int n = features.IncomeSupport.MagicNumber;
    Console.WriteLine($"     -- magic number is {n}");

    if (features.IncomeSupport.Page8.IsEnabled)
    {
        Console.WriteLine("Page 8 of Income Support");
    }

    RefreshIntervalsItemType startingIntervals = features.TwoWayMessaging.RefreshIntervals[0];
}

// host.Run();

// TODO: DOC: Limitation: all keys must be present in `appsettings.json`. Scanning other files might be added later.
// TODO: generate the IFeatureManager interface; generate interfaces for all classes we want exposed to the dev
// TODO: add <auto-generated> tag to generated files
// TODO: DOC: convention: if I have a Bagels feature in the project, I should not create a Bagels bool value in appsettings; I should create a Bagels object with a nested IsEnabled bool value
