namespace org.g14.FeatureFlags.Generation;

public static class Const
{
    /// <summary>
    /// The root item in appsettings containing feature flags data
    /// </summary>
    public const string FlagsRootKey = "FeatureFlags";

    public const string StringType = "string";
    public const string IntType = "int";
    public const string BoolType = "bool";

    public const string AutogeneratedHeader =
        """
        // <auto-generated>
        //     This file was generated by the Feature Flags source generator.
        //     Do not make changes in this file or your project might go boo-boo.
        //     If you make changes, your hard work will be lost when the code gets regenerated.
        // </auto-generated>
        """;
}