namespace org.g14.TypedConfig.Generator;

public static class Const
{
    public const string StringType = "string";
    public const string IntType = "int";
    public const string BoolType = "bool";

    public const string AutogeneratedHeader =
        """
        // <auto-generated>
        //     This file was generated by the Typed Config source generator.
        //     Do not make changes in this file or your project might go boo-boo.
        //     If you make changes, your hard work will be lost when the code gets regenerated.
        // </auto-generated>
        """;

    public static readonly string GeneratedCodeAttribute =
        $"""
        [System.CodeDom.Compiler.GeneratedCode("{typeof(Const).Assembly.GetName().Name}", "{typeof(Const).Assembly.GetName().Version?.ToString(3) ?? "unknown"}")]
        """;
}